name: Release Artifact

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Setup Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build a Composer Archives
        id: composer-archive
        run: |
          echo "Installing Composer dependencies..."
          composer install

          echo "Building PHAR..."
          pharName="rosetta-$GITHUB_REF_NAME.phar"
          composer build
          mv rosetta.phar "$pharName"

          echo "Removing dev dependencies that don't belong in archives..."
          rm -rf src/JavaScript/node_modules/
          rm -rf tests/
          rm -rf vendor-bin/

          echo "Building Composer archive..."
          zipName="rosetta-phpscript-$GITHUB_REF_NAME"
          composer archive --format=zip --file=$zipName

          echo "PACKAGIST_NAME=$zipName.zip" >> "$GITHUB_OUTPUT"
          echo "PHAR_NAME=$pharName" >> "$GITHUB_OUTPUT"

      - name: Upload a Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.composer-archive.outputs.PACKAGIST_NAME }}
            ${{ steps.composer-archive.outputs.PHAR_NAME }}
